[package]
name = "markdown_timesheet"
version = "0.6.0"
edition = "2021"
description = "A tool for processing markdown files to extract and format timesheet data"
license = "MIT"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0"
